---
- hosts: all
  vars:
    distributions:
      - trusty
      - trusty-backports
      - trusty-security
      - trusty-updates
    components:
      - main
      - restricted
      - universe
    date: "{{ ansible_date_time['year'] }}{{ ansible_date_time['month'] }}{{ ansible_date_time['day'] }}"
  vars_prompt:
    - name: "gpg_passphrase"
      prompt: "Enter passphrase"
  remote_user: root
  tasks:
    - name: Refresh mirrors
      command: aptly mirror update {{ item[0] }}-{{ item [1] }}
      with_nested:
        - distributions
        - components
      tags:
        - refresh-mirrors
    - name: Create new snapshots for tag
      command: aptly snapshot create {{ item[0] }}-{{ item[1] }}-{{ date }} from mirror {{ item[0] }}-{{ item[1] }}
      with_nested:
        - distributions
        - components
      tags:
        - create-snapshots
    - name: Publish snapshots for tag
      command: aptly publish snapshot -passphrase="{{ gpg_passphrase }}" -component="{{ components|join(',') }}" -distribution="{{ item }}-{{ date }}" {% for c in components %}{{ item }}-{{c}}-{{ date }} {% endfor -%} ubuntu
      with_items: distributions
      tags:
        - publish-snapshots
