---
- hosts: all
  vars_files:
    - vars_file.yml
  vars_prompt:
    - name: "gpg_passphrase"
      prompt: "Enter GPG passphrase"
    - name: "tag"
      prompt: "Enter tag name"
      when: tag is not defined
  remote_user: root
  tasks:
    - name: Create new snapshots for tag
      command: aptly snapshot create {{ item[0] }}-{{ item[1] }}-{{ tag }} from mirror {{ item[0] }}-{{ item[1] }}
      with_nested:
        - distributions
        - components
      tags:
        - create-snapshots
    - name: Publish snapshots for tag
      command: aptly publish snapshot -passphrase="{{ gpg_passphrase }}" -component="{{ components|join(',') }}" -distribution="{{ item }}-{{ tag }}" {% for c in components %}{{ item }}-{{c}}-{{ tag }} {% endfor -%} ubuntu
      with_items: distributions
      tags:
        - publish-snapshots
