---
- hosts: all
  vars:
    distributions:
      - trusty
      - trusty-backports
      - trusty-security
      - trusty-updates
    components:
      - main
      - restricted
      - universe
  vars_prompt:
    - name: "tag"
      prompt: "Enter tag name"
      when: tag is not defined
  remote_user: root
  tasks:
    - name: Unpublish snapshots
      command: aptly publish drop {{ item }}-{{ tag }} ubuntu
      with_items: distributions
      when: tag is defined
      tags:
        - unpublish-snapshots
    - name: Drop snapshots
      command: aptly snapshot drop {{ item[0] }}-{{ item[1] }}-{{ tag }}
      with_nested:
        - distributions
        - components
      when: tag is defined
      tags:
        - drop-snapshots
